- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable old nodejs
    ansible.builtin.comman: dnf module enable nodejs:18 -y
    
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
    