- name: catalogue
  hosts: localhost
  become: yes
  tasks:
  - name: disable old nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable old nodejs
    ansible.builtin.command: dnf module enable nodejs:18 -y
    
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
    
  - name: useradd roboshop
    ansible.builtin.user:
      name: roboshop

  - name: recursively remove app direcotry
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copying catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: deamon reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes