- name: catalogue
  hosts: localhost
  become: yes
  tasks:
  - name: disable old nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable old nodejs
    ansible.builtin.command: dnf module enable nodejs:18 -y
    
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
    
  - name: useradd roboshop
    ansible.builtin.user:
      name: roboshop

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app