- name: mongodb
  hosts: mongodb
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: install mongodb
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: start and enable
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: true
  
  - name: enable local host
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0

  - name: start and anable mongodb
    ansible.builtin.service:
      name: start and enable mongodb
      state: restarted

